
import React from 'react'


export const metadata = {
    title: 'Abra Oyun Bilgisayarı Serisi ile Gücü Hissedin | Monster',
    description: 'Generated by create next app',
  }

export default async function Home({params}) {

    
    return (
        <div className=''>
            
        </div>
    )
}
